### PR TITLE
[1.7.10] Update to ComputerCraft 1.65 and Thaumcraft 4.2.1.4

### PR DESCRIPTION
**Pull request by Katelyn-SN**
Multiple changes have been made also i suggest changing the project name to something better than "Turtle Fix" as its not just a fix for turtles anymore also i have updated the Thaumcraft Bore fix to Thaumcraft 4.2.1.4 but it may also support versions before and after this build number.

### CODE REVIEW

**Comment by thomas15v** [comment]
Can't auto-merge :cry:. Can you rebase your project to the latest commit: ecdf4f223409c44d01d97c917a7c9970871ddbb9 in direwolf . Also what would be a good name? Direwolf20_patches ?

**Comment by Katelyn-SN** [comment]
I'll have to do that when i get GIT all fixed up are you on IRC? I'm trying to get it worked out now i actually pasted that directly into github itself.

**Comment by thomas15v** [comment]
Ehm I am not very active on IRC actually :/. Its rather boring. But I can send you my skype if you want to. (sorry for the late response btw)

**Comment by Katelyn-SN** [comment]
We could do that I got all the changes waiting I just need to find the time to push a working model that is automegerable

**Comment by thomas15v** [comment]
I am on IRC now :). If you could start a PM, I can send you my skype xD.

**Pull request closed without merging**
